name: CI

on:
  pull_request:
    branches:
      - primary
  push:
    branches:
      - primary

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.7'
      - name: "Run tests"
        uses: julia-actions/julia-runtest@v1
